---
version: '3'

services:
  nodeapp:
    container_name: nodeapp
    build:
      context: nodeapp
      dockerfile: Dockerfile
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
    - "80:5000"