---
version: '3'

services:
  nodeapp:
    container_name: nodeapp
    build:
      context: nodeapp
      dockerfile: Dockerfile
    image: m1:5000/rayshoo/nodeapp:1.0
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
    - "80:5000"
    image: m1:5000/rayshoo/nginx:1.0